"""empty message

Revision ID: 83282a4384e3
Revises: 07110f71344f
Create Date: 2020-05-21 10:07:33.246908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83282a4384e3'
down_revision = '07110f71344f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.alter_column('Show', 'start_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('venue_id', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('venue_id', 'Show', 'Venue', ['id'], ['id'])
    op.alter_column('Show', 'start_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.drop_table('Artist')
    # ### end Alembic commands ###
