"""empty message

Revision ID: a95cf087e687
Revises: a9dcbbb60309
Create Date: 2020-05-20 10:49:23.822777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95cf087e687'
down_revision = 'a9dcbbb60309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.alter_column('Show', 'start_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('venue_id', 'Show', type_='foreignkey')
    op.drop_constraint('artist_id', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('artist_id', 'Show', 'Artist', ['id'], ['id'])
    op.create_foreign_key('venue_id', 'Show', 'Venue', ['id'], ['id'])
    op.alter_column('Show', 'start_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
